name: Generate new post template

on:
  workflow_dispatch:
    inputs:
      slug:
        description: 'Post slug'
        required: true

jobs:
  gen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create new branch
        run: git switch -c gen-new-post-$RANDOM

      - name: Test if slug is given
        run: test -n "${{ github.event.inputs.slug }}"

      - name: Generate template file
        run: make new slug="${{ github.event.inputs.slug }}"
        working-directory: ./b_source/

      - name: Add Git settings
        run: |
          git config --local user.email "139241+10sr@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

      - name: Git Add and Commit
        run: |
          git add ./b_source/content
          git commit -m "Commit post template, slug='${{ github.event.inputs.slug }}'"

      - name: Create Pull Request
        run: |
          git push origin HEAD
          gh pr create --title "Add post '${{ github.event.inputs.slug }}'" --body ""
        env:
          GH_TOKEN: ${{ github.token }}
